targets:
  $default:
    builders:
      functional_data_generator2|functional_data_generator2:
        enabled: true

builders:
  functional_data:
    target: ":functional_data_generator2"
    import: "package:functional_data_generator2/functional_data_generator2.dart"
    builder_factories: ["functionalData"]
    build_extensions: {".dart": [".functional_data.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
