name: Dart Publish

on: [push, pull_request]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: '>> Dart package functional_data2 <<'
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          dryRunOnly: false
          accessToken: ${{ secrets.PUB_LISH_OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_LISH_OAUTH_REFRESH_TOKEN }}
          relativePath: functional_data2
          skipTests: true

      - name: '>> Dart package functional_data_generator2 <<'
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          dryRunOnly: false
          accessToken: ${{ secrets.PUB_LISH_OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_LISH_OAUTH_REFRESH_TOKEN }}
          relativePath: functional_data_generator2
          skipTests: true
